name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se ejecuta cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/triviaBack
            git pull origin main
            npm install --production
            pm2 restart triviaBack
